### ISSUE TITLE
Don't say OPF when we mean PF

### ISSUE THREAD

**Issue by GabrielKS** [NREL-Sienna/PowerFlows.jl#40]
A trivial but important "bug": sometimes in the documentation, we incorrectly refer to a power flow problem as an _optimal_ power flow problem. As someone new to the field, this confused me. Example:
https://github.com/NREL-Sienna/PowerFlows.jl/blob/558a3374d901c984c82e4c9d4d8c15be801f9190/src/PowerFlowData.jl#L98

**Comment by rodrigomha** [comment]
Closed via #45
