### ISSUE TITLE
`solve_ac_powerflow!` on a previously solved system can fail

### ISSUE THREAD

**Issue by GabrielKS** [NREL-Sienna/PowerFlows.jl#47]
If `solve_ac_powerflow!` is called on a system and succeeds, we would expect that calling `solve_ac_powerflow!` a second time on that solved system would succeed and, ideally, produce the same answer. The system produced by
```julia
function create_system()
    sys = with_logger(() -> build_system(PSISystems, "RTS_GMLC_DA_sys"), SimpleLogger(Error))  # suppress logging
    remove_component!(sys, only(get_components(TwoTerminalHVDCLine, sys)))  # HVDC power flow not implemented yet
    sys_mod = deepcopy(sys)
    # Modify some things so reactive power redistribution succeeds
    for (component_type, component_name, new_limits) in [
        (RenewableDispatch, "113_PV_1",    (min = -30.0, max =  30.0))
        (ThermalStandard,   "115_STEAM_3", (min = -50.0, max = 100.0))
        (ThermalStandard,   "207_CT_1",    (min = -70.0, max =  70.0))
        (RenewableDispatch, "215_PV_1",    (min = -40.0, max =  40.0))
        (ThermalStandard,   "307_CT_1",    (min = -70.0, max =  70.0))
        (ThermalStandard,   "315_CT_8",    (min =   0.0, max =  80.0))
    ]
        set_reactive_power_limits!(get_component(component_type, sys, component_name), new_limits)
    end
    return sys
end
```

succeeds the first time around, if you define
```julia
PowerSystems.get_reactive_power_limits(::RenewableNonDispatch) = (min = 0.0, max = 0.0)
```
as a quick fix for https://github.com/NREL-Sienna/PowerFlows.jl/issues/39, but the second time there is an error:

<img width="1260" alt="Screenshot 2024-08-13 at 3 04 43 PM" src="https://github.com/user-attachments/assets/d1e1eba1-d297-4bc4-a8c4-27f9295425b7">

**Comment by rodrigomha** [comment]
It's a problem in PNM:

```
sys = create_system()

PowerSystems.get_reactive_power_limits(::RenewableNonDispatch) = (min = 0.0, max = 0.0)

check_reactive_power_limits = false
data = PowerFlowData(
        ACPowerFlow(; check_reactive_power_limits = check_reactive_power_limits),
        sys;
        check_connectivity = true,
    )

any(isnan.(data.bus_reactivepower_injection)) # false
any(isnan.(data.bus_reactivepower_withdrawals)) # false

solve_ac_powerflow!(sys)

data = PowerFlowData(
        ACPowerFlow(; check_reactive_power_limits = check_reactive_power_limits),
        sys;
        check_connectivity = true,
    )

any(isnan.(data.bus_reactivepower_injection)) # true
any(isnan.(data.bus_reactivepower_withdrawals)) # false
```

The bus data for reactivepower_injection is giving NaN after the first power flow call, and we need to investigate that.

**Comment by rodrigomha** [comment]
> It's a problem in PNM:
> 
> ```
> sys = create_system()
> 
> PowerSystems.get_reactive_power_limits(::RenewableNonDispatch) = (min = 0.0, max = 0.0)
> 
> check_reactive_power_limits = false
> data = PowerFlowData(
>         ACPowerFlow(; check_reactive_power_limits = check_reactive_power_limits),
>         sys;
>         check_connectivity = true,
>     )
> 
> any(isnan.(data.bus_reactivepower_injection)) # false
> any(isnan.(data.bus_reactivepower_withdrawals)) # false
> 
> solve_ac_powerflow!(sys)
> 
> data = PowerFlowData(
>         ACPowerFlow(; check_reactive_power_limits = check_reactive_power_limits),
>         sys;
>         check_connectivity = true,
>     )
> 
> any(isnan.(data.bus_reactivepower_injection)) # true
> any(isnan.(data.bus_reactivepower_withdrawals)) # false
> ```
> 
> The bus data for reactivepower_injection is giving NaN after the first power flow call, and we need to investigate that.

Nevermind this. The problem is that in the RTS system, the Sync Condenser units have base_power = 0.0.

Here is a fix:
```
sync_cond_names = ["214_SYNC_COND_1", "314_SYNC_COND_1", "114_SYNC_COND_1"]
for name in sync_cond_names
        g = get_component(StaticInjection, sys, name)
        set_base_power!(g, 100.0)
 end
```
